
_Screen.ISX.OnKey_Single_Quotes = .F.
_Screen.ISX.OnKey_Double_Quotes = .F.
_Screen.ISX.OnKey_Parenthesis = .F.
_Screen.ISX.OnKey_Brackets = .F.
_Screen.ISX.OnKey_VerticalBar = .F.
_Screen.ISX.Quote_Continue_NextLine = .f.
_Screen.ISX.Table_Sort_Fields = .F.
_Screen.ISX.Table_Repl_Commands = .T.
_Screen.ISX.Table_Struc_Commands = .T.
_Screen.ISX.Table_Replace_Remove_TableName_Before_With = .T.
_Screen.ISX.Table_Replace_Before_String = 'rtrava(0)'+Chr(13)
_Screen.ISX.Table_Replace_After_String = 'destravar()'+Chr(13)
_Screen.ISX.Use_UDF_Function = 'abrir'
